### ISSUE TITLE
/rep issue

### ISSUE THREAD

**Issue by ngblam2207** [viet-aus-it/vait-discord-bot#101]
**Describe the bug**
Cannot give "thanks @user" or "/rep give user"

**To Reproduce**
1. Go to #opportunity - #thread
2. /rep give user

**Expected behavior**
I cannot give thanks but other people can.
Assigned role to me as below.
![Assigned role](https://user-images.githubusercontent.com/55568360/167390043-72b84e05-358f-4f8c-852e-2b4be5190131.jpg)

**Screenshots**
![rep issue](https://user-images.githubusercontent.com/55568360/167390169-c048f6e6-ce65-463a-9179-686cdeecb595.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by samhwang** [comment]
Currently logging this as "**cannot replicate**".

**Comment by samhwang** [comment]
Closing this issue because @ngblam2207  cannot replicate as well.
