### ISSUE TITLE
Command to generate disclaimer

### ISSUE THREAD

**Issue by NNCT2904** [viet-aus-it/vait-discord-bot#105]
**Is your feature request related to a problem? Please describe.**
A function to generate a disclaimer as a text message. Joke or not, we may still need one in the future.

**Describe the solution you'd like**

- Use the keyword `disclaimer` to trigger the function
- Can choose between different languages: eng/vie, for example `disclaimer eng`
- It's a joke, for now

The disclaimer is like

`/disclaimer eng`
```
In case of an investigation by agencies under the Ministry of Public Security (or similar political organizations serving the ...
```

`/disclaimer vie`
```
Trong trường hợp nhóm này bị điều tra bởi các cơ quan trực thuộc bộ công an (hoặc các tổ chức chính trị tương tự ...
```

**Describe alternatives you've considered**
There is no alternative

**Additional context**
![image](https://user-images.githubusercontent.com/44821915/170216697-e5884465-cd3d-4a42-a419-61d4528b663b.png)

**Comment by NNCT2904** [comment]
Will do this after thesis :(

**Comment by nqngo** [comment]
Mình là hội ở Úc. Anh nghĩ mình ko nên mention bất cứ political statement nào. My take:

English
> In case of an investigation by any federal entity or similar, I do not have any involvement with this group or with the people in it, I do not know how I am here, probably added by a third party, I do not support any actions by the member of this group.

Vietnamese
> Trong trường hợp nhóm này bị điều tra bởi các cơ quan trực thuộc bộ công an (hoặc các tổ chức chính trị tương tự), tôi khẳng định mình không liên quan tới nhóm hoặc những cá nhân khác trong nhóm này. Tôi không rõ tại sao mình lại có mặt ở đây vào thời điểm này, có lẽ tài khoản của tôi đã được thêm bởi một bên thứ ba. Tôi cũng xin khẳng định rằng mình không hề giúp sức cho những hành động của các thành viên trong nhóm này.
