### ISSUE TITLE
Reminder

### ISSUE THREAD

**Issue by hp0210** [viet-aus-it/vait-discord-bot#13]
Requirement:
* /slash-command
* Default Time/ Allow user to set timezone
* How often: One-off / Interval 

**Message Format:**
 * /remind [timeformat] [message] # simple reminder once off
 * /remindSetTimezone [timezone] (e.g Australia/Brisbane)
 * /remindCheckTimezone
 * /remindList # return list of reminder with reminder id
 * /remindRemove [reminderId]

**TimeFormat:**
* 1m/h/d/w/M (current day + timeinterval)
* dd/MM/YYYY HH:mm

**TimeInterval:**
* 1m/h/d/w/M (repeat every ****)
* can extend to be more advanced if we can find a library that handle this for us

**Timezone:** 
* tz database time zones
* https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**reminderId**
* CUID 

**message**
* Message can be anything / text / link / message that mentioned s.o 
 
Note: the reminder is set on a specific channel that it is created from (channel specific)

**Comment by punkupoz** [comment]
Nếu em thêm Redis vào project để làm cái scheduler thì có ok không?
Nếu không cho em xin ý kiến để implement cái reminder.
@samhwang @dohaicuong  @hp0210

**Comment by samhwang** [comment]
@exNewbie tag được bt mà

**Comment by PyGeek03** [comment]
Idea for MVP: Only support reminder at daily granularity, not minutely. Only support AEST (as it's used by Australia's capital). 

When user trigger the command: the bot will convert the specified time to Unix timestamp, check if the timestamp has not passed, and store in a table in its database.

Background job: Everyday at 9am AEST, the bot will "wake up" and scan over this table. If any entry has a timestamp that has passed, then the bot will post its corresponding reminder, then delete this entry from the table. We could sort this table on the timestamp, but it's arguably a premature optimisation given the small expected usage of this feature.

Edge case: The current time is 8:59am AEST, and a user specifies their reminder's timestamp as 9am AEST of the same day. Then the bot scan could finish before this reminder is written to the database. However this edge case is sufficiently meaningless that we shouldn't worry about it.

Alternative: Any way to make this a cron job?

PS: I'm not sure if this issue would qualify as a good-first-issue, as anything to do with time could be complex enough to be its own project. It follows that the effort required for this project might be bigger than the expected usage.

**Comment by samhwang** [comment]
cái này hiện tại anh đang làm trong branch [`features/reminder`](https://github.com/viet-aus-it/vait-discord-bot/tree/feature/reminder) rồi, hiện tại thì đã có chức năng save reminder by time (e.g. remind @samhwang  on 03/04/2023 9:00am "Go to stand up").

Đang làm qua chuyện list + update reminder + tạo 1 script chạy lệnh fan out, + setup cron job chạy trong mỗi phút vẫn được.
