### ISSUE TITLE
Add Reaction Role Support

### ISSUE THREAD

**Issue by hieu-cognitia** [viet-aus-it/vait-discord-bot#134]
**Is your feature request related to a problem? Please describe.**
At the moment, members can assign roles to themselves by typing the `/role assign` command, and then choosing the roles one by one. If you want multiple roles or just want to update your roles, you have to do this multiple times, which is time-consuming and a bit frustrating.

**Describe the solution you'd like**
Lots of servers implemented a function called Reaction Role to solve this issue. You react to a message (from the bot) to assign and remove a role quickly. This eliminates the need to type a command multiple times.
A few bots that do this for inspiration:
[Carl Bot](https://carl.gg)
[MEE6](https://mee6.xyz/en/plugins/reaction-roles)
[YAGPDB](https://yagpdb.xyz/#features)

**Describe alternatives you've considered**
Alternatively, one could modify the `/role assign` commands to accept multiple choices, e.g. assign multiple roles at once. However Discord currently doesn't support this, so an implementation might be messy.
YAGPDB also has a slightly different implementation, where Admins can type the message, and the user reacts to it to get the role (instead of a message from the bot)

**Comment by hieu-cognitia** [comment]
Another alternative to consisder, suggested by Daniel:
[Discord Select Menu](https://discordjs.guide/interactions/select-menus.html#building-and-sending-select-menus)

**Comment by PyGeek03** [comment]
Should we just adopt one of the bots mentioned above instead of building a custom solution?

**Comment by samhwang** [comment]
lúc trước server đã xài YAGPDB nhưng mà sau đó cũng tạo bot riêng vì 2 lý do:

1 là mấy con bot kia có quá nhiều chức năng thừa mà server mình k dùng đến + thiếu những chức năng server cần
2 là chính vì nó có nhiều chức năng quá đâm ra nó lại scan hết tin nhắn + có save lại, nên hồi đầu mới lập ra bot riêng của server vì privacy.

**Comment by samhwang** [comment]
This can temporarily be resolved by server now having Role and channel menus. Closing.
