### ISSUE TITLE
Add reputation as birthday gift (and gift to gifter!)

### ISSUE THREAD

**Issue by PyGeek03** [viet-aus-it/vait-discord-bot#136]
**Is your feature request related to a problem? Please describe.**
Turn your birthday party to a "rửa rep" (reputation laundering) party. Now that's what I call a real party 😎

When A sends a `"Happy birthday @B!"` message, both A and B will receive 1 rep.

**Describe the solution you'd like**
There's a simple hack to give rep to B: Just add "happy birthday" and "chúc mừng sinh nhật" into [the list `matchers` in the file `src/config.ts`](https://github.com/viet-aus-it/vait-discord-bot/blob/73b2e3999ba5e3dd6c0f551855a01d9c427a1021/src/config.ts#L8). This works because this list configures which keywords in a message would trigger the function [`thankUserInMessage`](https://github.com/viet-aus-it/vait-discord-bot/blob/73b2e3999ba5e3dd6c0f551855a01d9c427a1021/src/commands/reputation/giveReputation.ts#L19), which adds 1 rep to the user tagged in that message.

As to how to give rep to A, I haven't thought much about it yet, but we might be able to reuse (or refactor) the code in `thankUserInMessage`.

**Describe alternatives you've considered**
As mentioned above, my solution for giving rep to B is a hack because the name of the function `thankUserInMessage` suggests that it is for thanking another user (and hence giving them 1 rep), not for directly giving rep. 

This could be fixed either by:
- Renaming this function to sth like `giveRepInMessage` (which describes what the function does rather than what it is for - I don't have enough experience to judge whether this is preferable or not), or by 
- Creating a separate function to do this (we can have this function handle giving rep to A as well - this has the added benefit of encapsulation and separation of concern). 

I might just be bike shedding though.

**Additional context**
Original idea credit: @jkiller295.

**Comment by samhwang** [comment]
Resolved by #142 .
