### ISSUE TITLE
Affiliate referral link/code function

### ISSUE THREAD

**Issue by samhwang** [viet-aus-it/vait-discord-bot#14]
Add a function to the bot to allow users to feed in their affiliate code and link for a service, and a command to get a random code/link for that service.

**Requirement:**
using /slash command
- add services -> values
- search services
- get a link:
  - strategy:
    - distribution randoms 
    - round-robin
- remove / add 
- admin
  -  can remove everything
- normal user
  - can remove their own link
  - only can add one link for one service (apply to all users)

**Comment by dohaicuong** [comment]
@samhwang @hp0210 Proprosed commands

SERVICE
  `referral services add $SERVICE_NAME`
    - add new service
    - check dupplication

  `referral services list`
    - return list of services

  `referral services list $TERM`
    - filter service list

LINK/CODE
  `referral new $SERVICE_NAME $LINK/CODE $EXPIRY_DATE(DD/MM/YYYY)`
    - add new link, code to service

  `referral peek`
    - randomly get a link, code not expired

  `referral yeet`
    - [ADMIN_ONLY] clean up expired referral code/link

**Comment by jkiller295** [comment]
> @samhwang @hp0210 Proprosed commands
> 
> SERVICE `referral services add $SERVICE_NAME` - add new service
> 
> `referral services list` - return list of services
> 
> `referral services list $TERM` - filter service list
> 
> LINK/CODE `referral new $SERVICE_NAME $LINK/CODE $EXPIRY_DATE(DD/MM/YYYY)` - add new link, code to service
> 
> `referral peek` - randomly get a link, code not expired
> 
> `referral yeet` - [ADMIN_ONLY] clean up expired referral code/link

Cái add service command nên là Admin command, chứ để end user add thì messy lắm

**Comment by samhwang** [comment]
Cái add service có khi không cần thiết, tại vì:

- Người dùng họ sẽ k biết có service nào mình hỗ trợ nếu như k list ra trước.
- What if họ cần add 1 service khác mà mình k hỗ trợ => gọi admin? thêm 1 bc phải train cho admin

Overall thats bad UX.

Anh nghĩ service thì cứ add dynamically thôi sẽ dễ hơn.

**Comment by jkiller295** [comment]
> * Người dùng họ sẽ k biết có service nào mình hỗ trợ nếu như k list ra trước.
Cái này mình có command để list mà
> * What if họ cần add 1 service khác mà mình k hỗ trợ => gọi admin? thêm 1 bc phải train cho admin
Cái này thì như feature request thôi

**Comment by samhwang** [comment]
> Cái này có command để list mà
> Cái này thì như feature request thôi

Thì đúng là có, nhưng mà nó làm add thêm 1-2 bước (at least) trước khi có thể actually add đc 1 cái code vào.

Em không nghĩ mình cần phải "Secure" như vậy cho anh em chia sẻ referral code cho các service.

**Comment by jkiller295** [comment]
> > Cái này có command để list mà
> > Cái này thì như feature request thôi
> 
> Thì đúng là có, nhưng mà nó làm add thêm 1-2 bước (at least) trước khi có thể actually add đc 1 cái code vào.
> 
> VD 1 trường hợp em nghĩ sẽ gặp:
> 
> * User add 1 code cho 1 service vì muốn chia sẻ code với anh em, nhưng service không đc hỗ trợ (mà user k biết?) => bot báo lỗi
> * User nghĩ muốn add service mới chưa được hỗ trợ => báo admin
> * Admin thêm service mới
> * User lúc đó mới đc add đc code
> 
> => Em nghĩ cái process này rất rườm rà cho 1 việc "mì ăn liền" như này. **Hiện tại** em không nghĩ mình cần phải "Secure" như vậy. Cái này cần flow cho end user đơn giản 1 chút chứ nhiều step quá thì lại discourage users from doing it.
> 
> Trong khi cùng cái flow trên thì it should be:
> 
> * User muốn add 1 code
> * Bot sẽ check xem service có chưa.
>   
>   * Nếu chưa, bot sẽ tạo 1 service mới
>   * Nếu có rồi, Bot sẽ lấy service có sẵn
> * Sau cùng, bot sẽ cho code vào service rồi print ra "đã thêm vào db" or something.
> 
> => Consolidate hết toàn bộ cái bước add service mới này vào 1 bước thôi.

Tại a đang implement cái workflow system trong cty software nên nghĩ tới cảnh giảm dc user input error thì giảm, làm cho nó chặt chẽ hơn. Vì nhiều khi user như Thiện sẽ cố gắng phá nó = cách enter invalid service rồi mình sẽ có 1 đống rác

**Comment by samhwang** [comment]
> Vì nhiều khi user [...] sẽ cố gắng phá nó = cách enter invalid service rồi mình sẽ có 1 đống rác.

Mấy cái referral service là external service cả, không liên quan tới con bot này, or Discord, or VAIT => mình đâu phải là người cần verify nó phải là rác hay không để mà cần cleanup đâu anh. Rác thì để đó rồi mình làm 1 cái admin process clean up hết mấy cái expired là xong thôi.

**Comment by hp0210** [comment]
Anh cũng nghĩ như @samhwang , anh nghĩ nên dynamically add vô luôn. Simplify hết
`referral new $SERVICE_NAME $LINK/CODE $EXPIRY_DATE(DD/MM/YYYY)`
- add new service
- nếu service có rùi thì notify, chưa có thì tạo service mới 

`referral list`
- return list of services

`referral list $TERM`
- filter service list

`referral random $SERVICE_NAME`
- randomly get a link, code not expired

Nice two have: / Admin Only
`referral combine $SERVICE_NAME1  $SERVICE_NAME2` // Combine two service
`referral delete $SERVICE_NAME1` // soft-delete only - marked service as deleted
`referral delete $SERVICE_NAME1 $LINK_TO_BE_DELETE` // delete link
