### ISSUE TITLE
A new command to remove members with specific role from a thread

### ISSUE THREAD

**Issue by jkiller295** [viet-aus-it/vait-discord-bot#153]
**Is your feature request related to a problem? Please describe.**
Occasionally somebody accidentally tags a role's name instead of a member's name (e.g. `@SA` when tagging `@sam`) in a thread and all members with that role get added inadvertently. 

**Describe the solution you'd like**
We need a command to remove everyone who has the tagged role from the thread quickly instead of removing one by one manually. 

`/removefromthread @rolesname`

The command should work in threads only.

**Comment by samhwang** [comment]
closed by #154
