### ISSUE TITLE
Move the prefix into a specific config

### ISSUE THREAD

**Issue by samhwang** [viet-aus-it/vait-discord-bot#16]
Currently, our functions are relying on hard-coded prefixes or keywords in the function to actually execute. This might make it harder in the long run if we want to change a keyword, or change a prefix to trigger a command.

Proposed solution: 
1/ create a config file, and then pass all the prefixes and keywords into there, so we can chagne it later if we want to.
2/ Or we only need a config for the prefixes. Each module should have their own config file for keywords and their command prefixes.
  e.g. we can put the `-` prefix in the main config file, and the command `rep` in the rep module, then we can piece them together by `${prefix}${command}`

Example:

```ts
// file: botConfig.ts
export const commandPrefix = '-';

// file: thanks/config.ts
export const checkRepCommand = 'rep';

// file: thanks/checkRep.ts
import { commandPrefix } from '../botConfig';
import { thanksCommand } from './config';

// do something here
export const checkReputation = async (msg: Message, prisma: PrismaClient) => {
  const keyword = `${commandPrefix}${thanksCommand}`;
  const hasKeyword = msg.content.startsWith(keyword);
  if (!hasKeyword) return;

  // the rest of the checkRep function
};
```

**Comment by hp0210** [comment]
Anh chưa rành cách ochestrate module trong node.js lắm. Nhưng anh nghĩ sẽ better nếu mình viết một cái module check prefix cho subModule, mấy cái như thanks bot register cái command với cái checkModule đó, rồi khi nào match đc cái prefix command as register thì sẽ invoke cái thanks modules async 

Như vậy vụ check message để biết cần invoke module nào thì đc centralised ở 1 module/funciton thôi.

**Comment by samhwang** [comment]
Em đồng ý vụ này. Nếu như file entrypoint mình có thể check luôn keyword prefix... rồi sau dó mình call function luôn từ đấy thì nó sẽ gọn gàng hơn là chạy 1 nùi function, nếu k fit sẽ exit.

Vậy sẽ phải sửa codebase của @dohaicuong trong file index.ts lại 1 tí, should be fine.
