### ISSUE TITLE
Command ticket to log and keep track a question

### ISSUE THREAD

**Issue by exNewbie** [viet-aus-it/vait-discord-bot#64]
**PROBLEM**
As number of members on Discord has been growing, there are questions which are missed or slip away. Plus, it is heard members don't want to interrupt ongoing conversations. They either wait for their turn (but most of the times they aren't patient) or silently walk away.
To resolve this issue, I propose to offer a command to Discord users to raise your questions.

**REQUIREMENTS**
- It is a Discord command (e.g. -question)
- User is able to tag user role(s)
- Moderators of the role will be notified.
- (Optional) a question can be marked as Resolved (or another status)

**Comment by samhwang** [comment]
This feature is now superseded by Discord's native thread feature, closing.
