### ISSUE TITLE
Shakespeare Paraphrase

### ISSUE THREAD

**Issue by NNCT2904** [viet-aus-it/vait-discord-bot#66]
A meme function to paraphrase sentences into old English style, just like Shakespeare!

- Use keyword `-shakespeare` to trigger the function
- If there is a message then paraphrase it.
- Support for emojis is optional.

Example:
input: `-shakespeare Thank you for sharing`
output: `Thank thee f'r sharing`

**Comment by samhwang** [comment]
command này muốn làm "việt hóa" tí có thể làm `-vanchuong` as in `-vănchương` luôn cũng được
