### ISSUE TITLE
Utility to get content from commands

### ISSUE THREAD

**Issue by NNCT2904** [viet-aus-it/vait-discord-bot#94]
**Is your feature request related to a problem? Please describe.**

Every function need to implement a way to remove the text "-command". This is bad because of code duplication.

**Describe the solution you'd like**

A middleware to handle input command, for example:

`-cowsay yolo `

Output:

`yolo`

**Describe alternatives you've considered**

Handle the command in every function. Bad idea.

**Comment by samhwang** [comment]
This can also be migrated to use a message middleware system. The (very rough) solution can be like this:

- Create a messge middleware pipeline
- The pipeline accepts a middleware function in this format. If there's no logic error (user not found...), run the `next()` function. If there is, return early and break the pipeline.
```ts
const syncMiddleware = (message: Message, next: NextFunc) => {

};

const asyncMiddleware = async (message: Message, next: NextFunc) => {

};
```
- The pipeline can then be initialized like this:
```ts
const createPipeline = (...middlewares?: MessageMiddleware[]) => {};

const pipeline = createPipeline(); // <= With no middleware
const pipeline = createPipeline(
  (_message, next) => {
    console.log('Hi, I am a test middleware!');
    next();
  }
); // <= With one default middleware
```
- The middlewares can then be loaded like so:
```ts
pipeline.use(middleware1, middleware2, middleware3); // <= Load in the middlewares
pipeline.execute(message); //<= execute the pipeline
```

**Comment by samhwang** [comment]
This is now superseded by #97, because when we force everyone to go through a command (except for `thanks @username`) the command will be parsed by Discord instead.
